ALTER TABLE public.interview_session
    ADD COLUMN IF NOT EXISTS mode character varying(20) DEFAULT 'general' NOT NULL,
    ADD COLUMN IF NOT EXISTS type character varying(20) DEFAULT 'GENERAL' NOT NULL,
    ADD COLUMN IF NOT EXISTS attitude_score integer,
    ADD COLUMN IF NOT EXISTS total_score integer,
    ADD COLUMN IF NOT EXISTS nonverbal jsonb;

ALTER TABLE public.question_keywords
    ADD COLUMN IF NOT EXISTS importance smallint DEFAULT 1,
    ADD COLUMN IF NOT EXISTS concept_description text,
    ADD COLUMN IF NOT EXISTS follow_up_question text;

UPDATE public.question_keywords
SET importance = COALESCE(importance, 1);

CREATE TABLE IF NOT EXISTS public.answer_keyword_result (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id bigint NOT NULL REFERENCES public.answer_log(id) ON DELETE CASCADE,
    keyword_id bigint NOT NULL REFERENCES public.question_keywords(id) ON DELETE CASCADE,
    similarity_score integer NOT NULL,
    is_covered boolean NOT NULL,
    reason text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.follow_up_answer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id bigint NOT NULL REFERENCES public.answer_log(id) ON DELETE CASCADE,
    keyword_id bigint NOT NULL REFERENCES public.question_keywords(id) ON DELETE CASCADE,
    follow_up_question text NOT NULL,
    follow_up_answer_text text NOT NULL,
    score integer NOT NULL
);
